// Generated by tools/generate_test_vectors_rs.py from Python Reticulum vectors.
// Do not edit by hand; regenerate from exported JSON instead.

use ed25519_dalek::SigningKey;
use rand_core::{CryptoRng, Error, RngCore};
use x25519_dalek::StaticSecret;

use crate::identity::PrivateIdentity;

pub const FIXED_IDENTITY_PRIVATE_KEY: [u8; 32] = [
    0xf0, 0xec, 0xbb, 0xa4, 0x9e, 0x78, 0x3d, 0xee, 0x14, 0xff, 0xc6, 0xc9, 0xf1, 0xe1, 0x25, 0x1e,
    0xfa, 0x7d, 0x76, 0x29, 0xe0, 0xfa, 0x32, 0x41, 0x3c, 0x5c, 0x59, 0xec, 0x2e, 0x0f, 0x6d, 0x6c,
];
pub const FIXED_IDENTITY_SIGNING_KEY: [u8; 32] = [
    0xf0, 0xec, 0xbb, 0xa4, 0x9e, 0x78, 0x3d, 0xee, 0x14, 0xff, 0xc6, 0xc9, 0xf1, 0xe1, 0x25, 0x1e,
    0xfa, 0x7d, 0x76, 0x29, 0xe0, 0xfa, 0x32, 0x41, 0x3c, 0x5c, 0x59, 0xec, 0x2e, 0x0f, 0x6d, 0x6c,
];

pub const FIXED_LINK_OWNER_PRIVATE_KEY: [u8; 32] = [
    0x6d, 0x55, 0xd6, 0x3e, 0xd7, 0xcf, 0x4c, 0x3f, 0x7f, 0x42, 0x06, 0xcb, 0xf4, 0xa1, 0xc0, 0xd1,
    0xa5, 0xfb, 0xcc, 0x31, 0x21, 0xd2, 0x96, 0xf6, 0xa4, 0xf5, 0x4c, 0x0f, 0x7f, 0x3f, 0x86, 0x8b,
];
pub const FIXED_LINK_OWNER_SIGNING_KEY: [u8; 32] = [
    0x8f, 0x3e, 0x3c, 0x49, 0x8d, 0x8b, 0xd4, 0xc6, 0x02, 0x5f, 0x3b, 0xb3, 0xed, 0xb3, 0x4f, 0x7e,
    0x18, 0xdf, 0xec, 0x53, 0xca, 0x6f, 0x6d, 0x1e, 0x1c, 0x6d, 0xb1, 0x6a, 0x6b, 0x7c, 0xf1, 0xc1,
];

pub const FIXED_ANNOUNCE_RNG_BYTES: [u8; 32] = [
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
    0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f,
];
pub const FIXED_ANNOUNCE_RANDOM_HASH_BYTES: [u8; 16] = [
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
];
pub const FIXED_ANNOUNCE_TIMESTAMP: u64 = 1_717_171_717;
pub const FIXED_LRPROOF_LINK_ID: [u8; 16] = [
    0x10, 0x32, 0x54, 0x76, 0x98, 0xba, 0xdc, 0xfe, 0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef,
];
pub const FIXED_FORWARDED_ANNOUNCE_TRANSPORT_ID: [u8; 16] = [
    0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff, 0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99,
];
pub const FIXED_LRPROOF_X25519_PRIVATE_KEY: [u8; 32] = [
    0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10,
    0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x20,
];
pub const FIXED_LRPROOF_ED25519_PRIVATE_KEY: [u8; 32] = [
    0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f, 0x30,
    0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3a, 0x3b, 0x3c, 0x3d, 0x3e, 0x3f, 0x40,
];

pub const ANNOUNCE_PACKET_HEX: &str =
    "01002419dca3c93718497b91990373df150300a8fd56cbca13577c24914cc4c13308b7d7f3e20bd39c55a4e636984655be343884f6da8c37b5f343568b185a20c63b5bf011a3d60ee805bb9e151371ea1d55556f233dfd9aa4cbd4a1e20001020304006659f60533cd993e7c1bd3fad38084751a9156092fe28495a25f11004c5e0a127863010164fb1614c5fa7712cbbb48fa175d2946a448c505b2066e636bf9e17b0d50470d";
pub const PATH_RESPONSE_PACKET_HEX: &str =
    "01002419dca3c93718497b91990373df15030ba8fd56cbca13577c24914cc4c13308b7d7f3e20bd39c55a4e636984655be343884f6da8c37b5f343568b185a20c63b5bf011a3d60ee805bb9e151371ea1d55556f233dfd9aa4cbd4a1e20001020304006659f60533cd993e7c1bd3fad38084751a9156092fe28495a25f11004c5e0a127863010164fb1614c5fa7712cbbb48fa175d2946a448c505b2066e636bf9e17b0d50470d";
pub const FORWARDED_ANNOUNCE_PACKET_HEX: &str =
    "5101aabbccddeeff001122334455667788992419dca3c93718497b91990373df150300a8fd56cbca13577c24914cc4c13308b7d7f3e20bd39c55a4e636984655be343884f6da8c37b5f343568b185a20c63b5bf011a3d60ee805bb9e151371ea1d55556f233dfd9aa4cbd4a1e20001020304006659f60533cd993e7c1bd3fad38084751a9156092fe28495a25f11004c5e0a127863010164fb1614c5fa7712cbbb48fa175d2946a448c505b2066e636bf9e17b0d50470d";
pub const EXPLICIT_PACKET_PROOF_HEX: &str =
    "0300960cd0b6fefcc623d5d6cbc7d9992f9400960cd0b6fefcc623d5d6cbc7d9992f940601b05157c9f0bea20d14c05051d9482a9c6f79b157eaabe8c13ad66a44850a3e061bef6de9eabfaf2cd1c168d59eca295527797b6329bafa7b3c5c144d7b0b8410f8bfb218405745f3f583892eae0c";
pub const LRPROOF_PACKET_HEX: &str =
    "0f001032547698badcfe0123456789abcdefffe6e1524c3cb1c64ae0e79ca1291aa1e86c3553b31bb7e670c6db1464da6859772ef31e23d8bbdca6e0bc72c0430c5483b4e2826b88e3251f7dc411392043ec0807a37cbc142093c8b755dc1b10e86cb426374ad16aa853ed0bdfc0b2b86d1c7c2001f4";
pub const PATH_REQUEST_NO_TRANSPORT_DATA_HEX: &str =
    "00112233445566778899aabbccddeeff66697865642d746167";
pub const PATH_REQUEST_WITH_TRANSPORT_DATA_HEX: &str =
    "00112233445566778899aabbccddeeffffeeddccbbaa9988776655443322110066697865642d746167";

#[derive(Copy, Clone)]
pub struct FixedRng {
    bytes: [u8; 32],
    offset: usize,
}

impl FixedRng {
    pub fn new(bytes: [u8; 32]) -> Self {
        Self { bytes, offset: 0 }
    }
}

impl RngCore for FixedRng {
    fn next_u32(&mut self) -> u32 {
        let mut buf = [0u8; 4];
        self.fill_bytes(&mut buf);
        u32::from_le_bytes(buf)
    }

    fn next_u64(&mut self) -> u64 {
        let mut buf = [0u8; 8];
        self.fill_bytes(&mut buf);
        u64::from_le_bytes(buf)
    }

    fn fill_bytes(&mut self, dest: &mut [u8]) {
        for byte in dest {
            *byte = self.bytes[self.offset % self.bytes.len()];
            self.offset += 1;
        }
    }

    fn try_fill_bytes(&mut self, dest: &mut [u8]) -> Result<(), Error> {
        self.fill_bytes(dest);
        Ok(())
    }
}

impl CryptoRng for FixedRng {}

pub fn decode_hex(hex: &str) -> Vec<u8> {
    assert_eq!(hex.len() % 2, 0, "hex string must be even-length");
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).expect("valid hex byte"))
        .collect()
}

pub fn fixed_private_identity() -> PrivateIdentity {
    PrivateIdentity::new(
        StaticSecret::from(FIXED_IDENTITY_PRIVATE_KEY),
        SigningKey::from_bytes(&FIXED_IDENTITY_SIGNING_KEY),
    )
}
